version: '3'
volumes:
  postgres-team29-data:
services:
  postgres:
    image: 'postgres:latest'
    hostname: postgres
    container_name: socialnet-db
    environment:
     POSTGRES_DB: socialnet
     POSTGRES_USER: admin
     POSTGRES_PASSWORD: passWd123
    ports:
    - "5455:5432"
    restart: unless-stopped
    volumes:
      - postgres-team29-data:/var/lib/postgresql/data
    networks:
      - "social-net"

  frontend:
    image: 'kohgutepdev/front:latest'
    container_name: frontend
    ports:
      - "8098:80"
    restart: unless-stopped
    networks:
      - "social-net"

  core:
    image: 'kohgutepdev/team29socialnet-core:latest'
    container_name: core-service
    environment:
      server.db.port: http://db-service:8081
      frontend.host: http://frontend:8098
      spring.mail.password: svsbxajrmngmshhs
      spring.mail.username: noreplaycomand28@gmail.com
      spring.mail.url: http://frontend:8098/change-password/
      cloudinary.cloud-name: dbjq1kufj
      cloudinary.api-key: 813445639385638
      cloudinary.api-secret: xiSz7HlLkmr1Gw4n5bpIyxYaIXA
    restart: unless-stopped
    networks:
      - "social-net"

  db:
    image: 'kohgutepdev/team29socialnet-db:latest'
    container_name: db-service
    depends_on:
      - postgres
    environment:
      spring.datasource.driver-class-name: org.postgresql.Driver
      spring.datasource.url: jdbc:postgresql://postgres:5432/socialnet
      spring.datasource.username: admin
      spring.datasource.password: passWd123
    restart: unless-stopped
    networks:
      - "social-net"

  migration-liquibase:
    container_name: migration-liquibase
    image: liquibase/liquibase
    depends_on:
      - postgres
    command: --url=jdbc:postgresql://postgres:5432/socialnet --changeLogFile=changelog.xml --username=admin --password=passWd123 update
    volumes:
      - ./db/src/main/resources/liquibase/changelog.xml:/liquibase/changelog.xml
      - ./db/src/main/resources/liquibase/structure:/liquibase/structure
    tty: true
    networks:
      - "social-net"

networks:
  social-net:
    driver: "bridge"